# Generated by Django 4.0.6 on 2022-09-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='No Phone Number Avaliable', max_length=30, null=True),
        ),
    ]
