# Generated by Django 4.0.6 on 2022-09-13 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producthistorylog',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
